- name: create /etc/swifty/conf/ dir
  file:
    path: /etc/swifty/conf/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create /root/.swysecrets/ dir
  file:
    path: /root/.swysecrets/
    state: directory
    owner: root
    group: root
    mode:  0700

- name: copy admd_secret.yaml
  template:
    src: admd_secret.j2
    dest: /root/.swysecrets/admd
    owner: root
    group: root
    mode: 0600

- name: copy gate_secret.yaml
  template:
    src: gate_secret.j2
    dest: /root/.swysecrets/gate
    owner: root
    group: root
    mode: 0600

- name: copy s3_secret.yaml
  template:
    src: s3_secret.j2
    dest: /root/.swysecrets/s3
    owner: root
    group: root
    mode: 0600


- name: copy gate config
  template:
    src: gate.j2
    dest: /etc/swifty/conf/gate.yaml
    owner: root
    group: root
    mode: 0640

- name: copy admd config
  template:
    src: admd.j2
    dest: /etc/swifty/conf/admd.yaml
    owner: root
    group: root
    mode: 0640

- name: copy s3 config
  template:
    src: s3.j2
    dest: /etc/swifty/conf/s3.yaml
    owner: root
    group: root
    mode: 0640

- name: copy mime.types files
  copy:
    src: mime.types
    dest: /etc/swifty/conf/mime.types

- name: docker run s3
  shell: docker run -d --net=host --name=swys3 --restart always -v /home/swifty-volume:/home/swifty-volume -v /etc/swifty:/etc/swifty -v /root/.swysecrets:/root/.swysecrets -v /home/swifty-volume:/home/swifty-volume swiftycloudou/s3
