- name: install mariadb
  package:
    name:
      - mariadb-server
      - mariadb-server-utils
      - python3-devel
      - mysql-devel
      - gcc
    state: latest
  when: (ansible_distribution == "Fedora")

- name: install mariadb
  package:
    name:
      - mariadb-server
      - libmysqlclient-dev
      - gcc
      - python3-dev
    state: latest
  when: (ansible_distribution == "Ubuntu")

- name: enable and start mariadb service
  systemd:
    name: mariadb
    enabled: yes
    masked: no
    state: started
    
- name: Install the mysqlclient module
  pip:
    name: mysqlclient
    executable: pip3

#- name: change password for mariadb root user
#  mysql_user:
#    login_user: root
#    login_password: ''
#    name: root
#    host_all: yes
#    password: "{{ mariadb_root_password }}"
#    priv: '*.*:ALL'
