---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: python3
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - ec2

- hosts: dep-gw
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - docker
   - nginx-reverse-proxy/gw

- hosts: dep-mw
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
   - include_vars: group_vars/all.yml
  roles:
   - docker 
   - nginx-reverse-proxy/mw