- name: create /etc/swifty/conf/ dir
  file:
    path: /etc/swifty/conf/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create /root/.swysecrets/ dir
  file:
    path: /root/.swysecrets/
    state: directory
    owner: root
    group: root
    mode:  0700

- name: create functions dir
  file:
    path: /home/swifty-volume/functions/
    state: directory
    owner: root
    group: root
    mode:  0755

- name: create packages dir
  file:
    path: /home/swifty-volume/packages/
    state: directory
    owner: root
    group: root
    mode:  0755

- name: copy admd_secret.yaml
  template:
    src: admd_secret.j2
    dest: /root/.swysecrets/admd
    owner: root
    group: root
    mode: 0600

- name: copy gate_secret.yaml
  template:
    src: gate_secret.j2
    dest: /root/.swysecrets/gate
    owner: root
    group: root
    mode: 0600

- name: copy s3_secret.yaml
  template:
    src: s3_secret.j2
    dest: /root/.swysecrets/s3
    owner: root
    group: root
    mode: 0600

- name: copy kubeconfig
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "/etc/swifty/conf/kubeconfig"
    remote_src: True

- name: copy gate config
  template:
    src: gate.j2
    dest: /etc/swifty/conf/gate.yaml
    owner: root
    group: root
    mode: 0640

- name: copy admd config
  template:
    src: admd.j2
    dest: /etc/swifty/conf/admd.yaml
    owner: root
    group: root
    mode: 0640

- name: copy s3 config
  template:
    src: s3.j2
    dest: /etc/swifty/conf/s3.yaml
    owner: root
    group: root
    mode: 0640

- name: copy scraper config
  template:
    src: scraper.j2
    dest: /etc/swifty/conf/scraper.yaml
    owner: root
    group: root
    mode: 0640

- name: copy go deployment
  copy:
    src: service-golang.yaml
    dest: /root/service-golang.yaml

- name: copy swift deployment
  copy:
    src: service-swift.yaml
    dest: /root/service-swift.yaml

- name: copy python deployment
  copy:
    src: service-python.yaml
    dest: /root/service-python.yaml

- name: copy ruby deployment
  copy:
    src: service-ruby.yaml
    dest: /root/service-ruby.yaml

- name: copy nodejs deployment
  copy:
    src: service-nodejs.yaml
    dest: /root/service-nodejs.yaml

- name: copy csharp deployment
  copy:
    src: service-csharp.yaml
    dest: /root/service-csharp.yaml

- name: kubectl create golang builder
  shell: kubectl create -f /root/service-golang.yaml

- name: kubectl create swift builder
  shell: kubectl create -f /root/service-swift.yaml

- name: kubectl create python builder
  shell: kubectl create -f /root/service-python.yaml

- name: kubectl create ruby builder
  shell: kubectl create -f /root/service-ruby.yaml

- name: kubectl create nodejs builder
  shell: kubectl create -f /root/service-nodejs.yaml

- name: kubectl create csharp builder
  shell: kubectl create -f /root/service-csharp.yaml

- name: create home dir
  file:
    path: /home/swifty/clone/.shared/swifty.demo
    state: directory
    owner: root
    group: root
    mode:  0700

- name: install git
  package:
    name: git
    state: latest

- name: clone demo apps repo
  git:
    repo: 'https://github.com/swiftycloud/swifty.demo'
    dest: /home/swifty/clone/.shared/swifty.demo
    version: master

- name: create /var/run/swifty dir
  file:
    path: /var/run/swifty
    state: directory
    owner: root
    group: root
    mode:  0700

- name: docker run gate
  shell: docker run -d --net=host --name=swygate --restart always -v /home/swifty/clone:/home/swifty/clone -v /home/swifty-volume:/home/swifty-volume -v /etc/swifty:/etc/swifty -v /root/.swysecrets:/root/.swysecrets -v /var/run/swifty/:/var/run/swifty/ registry.gitlab.com/swiftyteam/swifty/gate

- name: docker run admd
  shell: docker run -d --net=host --name=swyadmd --restart always -v /home/swifty-volume:/home/swifty-volume -v /etc/swifty:/etc/swifty -v /root/.swysecrets:/root/.swysecrets registry.gitlab.com/swiftyteam/swifty/admd

- name: docker run swydbscr
  shell: docker run -d --net=host --name=swydbscr --restart always -v /etc/swifty:/etc/swifty registry.gitlab.com/swiftyteam/swifty/swydbscr
