- name: check if certs volume exists
  command: docker volume inspect certs
  register: certs_volume_exists
  failed_when: false

- name: create certs volume
  command: docker volume create --name certs
  when: certs_volume_exists|failed

- name: check if certs-data exists
  command: docker volume inspect certs-data
  register: certs_data_exists
  failed_when: false

- name: create certs-data
  command: docker volume create --name certs-data
  when: certs_data_exists|failed

#- name: certbot container
#  docker:
#    name: certbot
#    image: deliverous/certbot
#    state: started
#    net: host
#    volumes:
#    - certs:/etc/letsencrypt
#    - certs-data:/data/letsencrypt

- name: create certbot
  shell: |
    docker run -t --rm \
    -v certs:/etc/letsencrypt \
    -v certs-data:/data/letsencrypt \
    --net=host \
    deliverous/certbot \
    certonly \
    --standalone \
    --agree-tos \
    --non-interactive \
    --email {{ cert_admin_email }} \
    -d 18.219.255.245.nip.io
