# ansible
ansible_ssh_user: fedora
ansible_ssh_private_key_file:
ansible_python_interpreter: /usr/bin/python3

# Kubernetes
token:  # use 'kubeadm token generate' for token creation
pod_network_cidr: "10.244.0.0/16"


# tags for docker images; we can replace it with extra_vars
tag_swifty: latest
tag_ui: latest
tag_connector: latest

# passwords
mariadb_root_password:
mariadb_keystone_password:
mongodb_admin_password:
mongodb_swygate_password:
mongodb_swyadmd_password:
mongodb_s3_password:
keystone_swyadmin_password:
keystone_swyui_password:
keystone_admin_password:  # without special chars
keystone_swydbscr_password:
rabbitmq_root_password:
rabbitmq_s3_password:
pgr_token:
s3_token:  # hex encoded; run 'swysg -b' or 'openssl rand -hex 16'
s3_secret_key:  # hex encoded; run 'swysg -b' or 'openssl rand -hex 16'
mw_secpass:  # hex encoded; run 'swysg -b' or 'openssl rand -hex 16'

#connector
app_env: production
app_key:
mail_from:
mail_from_name:
main_domain:
sendgrid_api_key:
sendgrid_welcome_tpl:
sendgrid_password_reset_tpl:
sendgrid_verification_tpl:

# tinc vpn
netname: nyc3
vpn_interface: tun0
vpn_netmask: 255.255.255.0
vpn_subnet_cidr_netmask: 32

# let's encrypt
cert_admin_email:

# for customization of this, use --extra-vars and omit "default_" in key, otherwise default will be applied

default_dashboard_domain_name:
default_api_domain_name:
default_s3_domain_name:
default_connector_domain_name:

# use separate token for swifty repo
registry_host: registry.gitlab.com
docker_username: gitlab+deploy-token-61962
docker_password: UtUqKnNBn6AjBAUFdgE2

# use separate token for swifty-ui repo
ui_registry_host: registry.gitlab.com
ui_docker_username: gitlab+deploy-token-61963
ui_docker_password: uenX89Py5vXNvakpzqfk

# use separate token for swifty-connector repo
connector_registry_host: registry.gitlab.com
connector_docker_username: gitlab+deploy-token-61964
connector_docker_password: 5J2g7nxtS1fkvBuqvNfB

# system
systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
remote_host_ip: '%'
allow_local_sign: true
