- name: install libselinux
  dnf:
    name: libselinux-python3
    state: latest

- name: Disable selinux
  selinux:
    state: disabled

- name: Install the mysqlclient module
  pip:
    name: docker-py
    executable: pip3

- name: install docker engine
  dnf:
    name: docker
    state: latest
- name: enable  docker service
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: start docker service
  systemd: state=started name=docker

- name: Log into swifty registry
  docker_login:
    registry: "{{ registry_host }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
