- name: add mongodb repo
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: copy collections file
  copy:
    src: collections.js
    dest: /root/collections.js
- name: install mongodb
  dnf:
    name:
      - mongodb
      - mongodb-server
    state: latest
- name: enable  mongodb service
  systemd:
    name: mongod
    enabled: yes
    masked: no
- name: start mongodb service
  systemd: state=started name=mongod
- name: Install the pymongo module
  pip:
    name: pymongo
- name:  add admin user
  mongodb_user:
    database: admin
    name: admin
    password: ew8VKv8Kq79C
    roles: readWrite,userAdminAnyDatabase,dbAdminAnyDatabase,dbAdminAnyDatabase
    state: present
- name:  add swygate user
  mongodb_user:
    login_user: admin
    login_password: ew8VKv8Kq79C
    database: swifty
    name: swygate
    password: dt3962zew1b
    roles: readWrite,dbAdmin,userAdmin,dbOwner
    state: present
- name:  add swyadmd user
  mongodb_user:
    login_user: admin
    login_password: ew8VKv8Kq79C
    database: swifty
    name: swyadmd
    password: 1a84cd9148bG8
    roles: readWrite,dbAdmin,userAdmin,dbOwner
    state: present
- name:  add swifty-s3 user
  mongodb_user:
    login_user: admin
    login_password: ew8VKv8Kq79C
    database: swifty-s3
    name: swifty-s3
    password: aebik0eichie0eXu
    roles: readWrite,dbAdmin,userAdmin,dbOwner
    state: present
- name: create collections
  shell: "mongo swifty /root/collections.js"
