---

- name: download prometheus node exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /root/node_exporter-0.17.0.linux-amd64.tar.gz

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "/root/node_exporter-0.17.0.linux-amd64.tar.gz"
    dest: "/root"
    creates: "/root/node_exporter-0.17.0.linux-amd64/node_exporter"

- name: create symlink to /usr/bin
  file:
    src: "/root/node_exporter-0.17.0.linux-amd64/node_exporter"
    path: "/usr/bin/node_exporter"
    state: link

- name: create systemd service unit
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
    owner: root
    group: root
    mode: 0644

- name: ensure prometheus node exporter service is enabled and started
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes
