---
 - name: Install the boto module
   pip:
     name: boto

 - name: Provision EC2 Box
   local_action:
     module: ec2
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
     assign_public_ip: yes
     wait: true
     count: 1
   register: ec2

 - debug: var=item
   with_items: ec2.instances

 - name: add host
   add_host:
     hostname: "{{ item.public_ip }}"
     groups:
       - swy-core
   with_items: '{{ ec2.instances }}'

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host="{{item.public_ip}}" port=22 delay=60 timeout=320 state=started
   with_items: '{{ ec2.instances }}'
