apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: swy-go-service
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: /
  name: swy-go-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: swy-go-service
  template:
    metadata:
      labels:
        deployment: swy-go-service
        swyservice: golang
      name: swy-go-service
    spec:
      containers:
      - name: golang-service
        image: "swifty/golang"
        imagePullPolicy: Never
        env:
        - name: SWD_INSTANCE
          value: "service"
        - name: SWD_PORT
          value: "8687"
        - name: SWD_LANG
          value: "golang"
        - name: SWD_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /go/src/swycode
          name: code
        - mountPath: /go-pkg
          name: packages
      volumes:
      - hostPath:
          path: /home/swifty-volume/functions
        name: code
      - hostPath:
          path: /home/swifty-volume/packages
        name: packages
