- name: Log into swifty registry
  shell: "docker login {{ ui_registry_host }} -u {{ ui_docker_username }} -p {{ ui_docker_password }}"

- name: cleanup ui containers, if running
  shell: "docker stop ui || true && docker rm ui || true"

- name: pull new ui image
  shell: docker pull registry.gitlab.com/swiftyteam/swifty-dashboard-v2:{{tag_ui}}

- name: start ui
  shell: docker run -d -p 80:80 -p 443:443 --name ui --restart always -v /root/nginx.conf:/etc/nginx/conf.d/default.conf -v certs:/etc/letsencrypt  -v certs-data:/data/letsencrypt -v /root/swifty.config.json:/html/swifty.config.json:ro registry.gitlab.com/swiftyteam/swifty-dashboard-v2
